[tool.poetry]
name = "pollution_analysis"
version = "0.1.0"
description = ""
authors = ["ChristinaLast <christina.last@outlook.com>"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.26.0"
pandas = "^1.3.5"
geopandas = "^0.9.0"
open-geo-engine = {git = "https://github.com/AQ-AI/open-geo-engine.git", rev = "e1242d525db7b20f4675647738f867dd0ad7ead2"}
Shapely = "^1.8.1"
matplotlib = "^3.5.1"
plotly = "^5.6.0"
ipykernel = "^6.9.1"
nbformat = "^5.1.3"
joblib = "^1.1.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^21.12b0"
flake8 = "^4.0.1"
pycodestyle = "^2.8.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
